import { ArrowUpRight, Check, Gauge, Headphones, Layers3, MousePointerClick, Smartphone, Sparkles, Wrench } from "lucide-react";
import Link from "next/link";
import { chatbotOffer, faqs, maintenanceOptions, packages, processSteps, projects, sectors } from "@/content/site";
import { ButtonLink, SectionHeading } from "./ui";

export function ServicesSection() {
  const services = [
    { icon: Layers3, title: "Strategie en structuur", text: "Een logische paginastructuur vanuit je doelgroep, aanbod en belangrijkste bedrijfsdoel." },
    { icon: Sparkles, title: "Maatwerk webdesign", text: "Een eigen visuele richting die aansluit op je merk—zonder standaardtemplate." },
    { icon: MousePointerClick, title: "Conversie en contact", text: "Gerichte CTA's, formulieren, WhatsApp, afspraken of offertes zonder onnodige drempels." },
    { icon: Smartphone, title: "Responsive ontwikkeling", text: "Snel, toegankelijk en prettig te gebruiken op mobiel, tablet en desktop." },
    { icon: Gauge, title: "SEO en performance", text: "Een technisch sterke, vindbare basis die past bij het gekozen pakket." },
    { icon: Headphones, title: "Uitbreiding en ondersteuning", text: "Later pagina's, koppelingen of functies toevoegen en alleen onderhoud inkopen wanneer nodig." },
  ];
  return <section id="diensten-overzicht" className="py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHeading eyebrow="Onze diensten" title="Van eerste richting tot een website die klaar is om te groeien" description="Sitora brengt strategie, ontwerp, inhoud en techniek samen in één helder traject. Iedere keuze wordt afgestemd op jouw bedrijf en doelgroep." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(({ icon: Icon, title, text }) => <article key={title} className="group rounded-2xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-orange-200 hover:shadow-xl hover:shadow-slate-900/5"><span className="grid size-12 place-items-center rounded-xl bg-blue-950 text-orange-400"><Icon className="size-6" /></span><h3 className="mt-5 text-xl font-black tracking-[-0.03em] text-slate-950">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>;
}

export function SectorsSection() {
  return <section id="branches" className="bg-slate-100 py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHeading eyebrow="Websites voor iedere branche" title="Een eigen aanpak voor ieder bedrijf en iedere doelgroep" description="Van lokale dienstverlener tot groeiende organisatie: inhoud, uitstraling en functionaliteit sluiten aan op de manier waarop jouw klanten kiezen." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{sectors.map((sector, index) => <Link key={sector.slug} href={`/${sector.slug}`} className="group flex min-h-52 flex-col justify-between rounded-2xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-orange-300 hover:shadow-lg"><span className="text-xs font-black text-orange-800">{String(index + 1).padStart(2, "0")}</span><div><h3 className="text-xl font-black text-slate-950">{sector.plural}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{sector.description}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-black text-slate-950">Bekijk mogelijkheden <ArrowUpRight className="size-4" /></span></div></Link>)}</div></div></section>;
}

export function PackagesSection({ showIntro = true, preview = false }: { showIntro?: boolean; preview?: boolean }) {
  return <section className="bg-[#f6f3ed] py-24 sm:py-32 lg:py-40" id="pakketten"><div className="mx-auto max-w-[86rem] px-5 sm:px-8 lg:px-10">{showIntro ? <SectionHeading center={!preview} eyebrow="Eenmalige websitepakketten" title="Kies de basis die past bij je ambitie" description="Geen standaardtemplate en geen verplicht abonnement. Ieder pakket wordt inhoudelijk en visueel afgestemd op je bedrijf." /> : null}<div className={`mt-12 grid items-stretch gap-4 md:grid-cols-2 xl:grid-cols-4 ${preview ? "" : "sm:mt-16"}`}>{packages.map((item) => <article key={item.name} className={`relative flex flex-col rounded-[1.25rem] border bg-white p-6 text-slate-950 sm:p-7 ${item.featured ? "border-orange-700 ring-1 ring-orange-700" : "border-slate-900/15"}`}>{item.featured ? <span className="absolute right-5 top-5 max-w-28 rounded-full bg-orange-700 px-3 py-1 text-center text-[10px] font-black uppercase tracking-wider text-white">Voor uitgebreide websites</span> : null}<p className="pr-28 text-sm font-black text-orange-800">{item.name}</p><div className="mt-8"><span className="whitespace-nowrap text-4xl font-black tracking-[-0.055em]">{item.price}</span><span className="mt-2 block text-xs text-slate-700">{item.cadence}</span></div><p className="mt-4 text-xs font-bold text-slate-700">{item.audience}</p><p className="mt-5 leading-7 text-slate-600">{item.description}</p><details open={!preview} className="group mt-7 flex-1 border-y border-slate-900/15 py-4"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between font-black marker:hidden">Inhoud en grenzen<span className="text-xl text-orange-800 transition-transform group-open:rotate-45">+</span></summary><ul className="mt-4 space-y-3 pb-2">{item.features.map((feature) => <li key={feature} className="flex gap-3 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-orange-800" />{feature}</li>)}</ul><p className="mt-4 text-xs font-bold text-slate-700">{item.notFor}</p>{!preview ? <p className="mt-3 text-xs leading-5 text-slate-700">Niet standaard inbegrepen: {item.exclusions.join(", ")}.</p> : null}</details>{!preview ? <p className="mt-5 text-xs leading-5 text-slate-700">{item.ownership}</p> : null}<ButtonLink href={`/contact?pakket=${item.id}#advies`} variant={item.featured ? "primary" : "secondary"} className="mt-7 w-full">Kies {item.name}</ButtonLink></article>)}</div><p className="mt-5 text-center text-xs text-slate-700">Alle prijzen zijn exclusief btw. Definitieve pagina&apos;s, inhoud, correctierondes, planning, betaling en eigendom worden vóór de start in de offerte bevestigd.</p>{preview ? <div className="mt-8 text-center"><ButtonLink href="/pakketten" variant="secondary">Vergelijk alle pakketten</ButtonLink></div> : null}</div></section>;
}

export function MaintenanceSection() {
  return <section id="onderhoud" className="bg-[#07111f] py-24 text-white sm:py-32"><div className="mx-auto max-w-[86rem] px-5 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><SectionHeading inverse eyebrow="Onderhoud en bezoekershulp" title="Onderhoud wanneer jij het nodig hebt" /><div><p className="max-w-xl text-lg leading-8 text-slate-300">Bij Sitora zit je niet vast aan een verplicht onderhoudsabonnement. Je betaalt alleen wanneer je onderhoud, ondersteuning of een chatbot nodig hebt.</p><Link href="/website-onderhoud" className="mt-4 inline-flex min-h-11 items-center font-black text-orange-300 underline decoration-2 underline-offset-4">Alles over websiteonderhoud</Link></div></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{maintenanceOptions.map((item) => <article key={item.id} className="rounded-3xl border border-white/15 bg-white/5 p-7 sm:p-9"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-black text-orange-300">{item.name}</p><p className="mt-3 text-4xl font-black tracking-[-.05em]">{item.price}</p><p className="mt-2 text-xs text-slate-300">{item.cadence}</p></div><Wrench className="size-8 text-orange-300" /></div><ul className="mt-7 grid gap-3">{item.features.map((feature) => <li key={feature} className="flex gap-3 text-sm text-slate-200"><Check className="mt-0.5 size-4 shrink-0 text-orange-300" />{feature}</li>)}</ul><ButtonLink href={`/contact?dienst=${item.id}#advies`} variant="dark" className="mt-8">Plan {item.name.toLowerCase()}</ButtonLink></article>)}<article className="rounded-3xl border border-orange-400 bg-orange-500 p-7 text-[#07111f] sm:p-9"><p className="text-sm font-black">Chatbot voor je website</p><p className="mt-3 text-4xl font-black tracking-[-.05em]">{chatbotOffer.price}</p><p className="mt-2 text-xs font-bold text-slate-950">{chatbotOffer.cadence}</p><p className="mt-5 leading-7 text-slate-950">{chatbotOffer.description}</p><ul className="mt-7 grid gap-3">{chatbotOffer.features.map((feature) => <li key={feature} className="flex gap-3 text-sm font-bold"><Check className="mt-0.5 size-4 shrink-0" />{feature}</li>)}</ul><ButtonLink href="/contact?dienst=website-chatbot#advies" variant="secondary" className="mt-8 w-full">Chatbot aanvragen</ButtonLink><Link href="/chatbot-voor-je-website" className="mt-4 inline-flex min-h-10 items-center text-sm font-black underline decoration-2 underline-offset-4">Bekijk prijs en mogelijkheden</Link></article></div><p className="mt-9 border-l-2 border-orange-300 pl-5 text-lg font-black">Geen verplicht abonnement. Je betaalt alleen wanneer je onderhoud of de eenmalige chatbotinstallatie nodig hebt.</p></div></section>;
}

export function PackageComparison() {
  const rows = [
    ["Aantal pagina's", "Tot 5", "Tot 10", "Tot 20", "Onbeperkt binnen scope"],
    ["Ontwerp", "Professioneel maatwerk", "Premium maatwerk", "Exclusief maatwerk", "Volledig op maat"],
    ["SEO", "Basis", "Geavanceerde basis", "Geavanceerd + optimalisatie", "Strategie op maat"],
    ["Blog of nieuws", "—", "Inbegrepen", "Inbegrepen", "Op maat"],
    ["Portfolio of cases", "—", "—", "Inbegrepen", "Op maat"],
    ["Afspraken of offertes", "Contactformulier", "Conversiegerichte CTA's", "Module inbegrepen", "Boeking of maatwerkflow"],
    ["Koppelingen", "WhatsApp en socials", "Maps en Reviews", "Analytics en Search Console", "API's, portaal of dashboard"],
    ["Verplicht onderhoud", "Nee", "Nee", "Nee", "Nee"],
  ];
  return <section data-analytics-view="pricing_compare_view" className="bg-[#f6f3ed] pb-24 sm:pb-32"><div className="mx-auto max-w-[86rem] px-5 sm:px-8 lg:px-10"><SectionHeading eyebrow="Vergelijk de pakketten" title="De verschillen naast elkaar" description="De vergelijking toont de standaardscope. Voor Maatwerk worden functies, planning en investering vooraf concreet vastgelegd." /><div className="mt-10 grid gap-4 md:hidden">{packages.map((item, packageIndex) => <article key={item.id} className="rounded-2xl bg-white p-5"><h3 className="text-xl font-black text-slate-950">{item.name}</h3><dl className="mt-4 space-y-3">{rows.map((row) => <div key={row[0]} className="grid grid-cols-[.9fr_1.1fr] gap-3 text-sm"><dt className="font-bold text-slate-900">{row[0]}</dt><dd className="text-slate-600">{row[packageIndex + 1]}</dd></div>)}</dl></article>)}</div><div className="mt-10 hidden overflow-x-auto rounded-[1.25rem] bg-white md:block"><table className="w-full min-w-[850px] border-collapse text-left text-sm"><caption className="sr-only">Vergelijking van Starter, Business, Premium en Maatwerk</caption><thead className="bg-[#07111f] text-white"><tr><th scope="col" className="p-4">Onderdeel</th>{packages.map((item) => <th scope="col" className={`p-4 ${item.featured ? "bg-orange-700" : ""}`} key={item.id}>{item.name}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row[0]} className={index % 2 ? "bg-slate-50" : "bg-white"}>{row.map((cell, cellIndex) => cellIndex === 0 ? <th scope="row" className="p-4 font-black text-slate-900" key={cell}>{cell}</th> : <td className="p-4 text-slate-600" key={`${row[0]}-${cellIndex}`}>{cell}</td>)}</tr>)}</tbody></table></div></div></section>;
}

export function ProcessSection({ full = false }: { full?: boolean }) {
  return <section className="editorial-grid bg-[#07111f] py-24 text-white sm:py-32 lg:py-40"><div className="mx-auto max-w-[86rem] px-5 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-[1fr_.65fr] lg:items-end"><SectionHeading inverse eyebrow="Van aanvraag tot overdracht" title="Zes duidelijke beslismomenten" /><p className="max-w-xl text-lg leading-8 text-slate-400">Je weet steeds waar we staan, wat Sitora doet, wat we van je nodig hebben en wat de volgende stap is.</p></div><div className="mt-16 border-t border-white/15">{processSteps.map((step) => <article key={step.number} className="grid gap-4 border-b border-white/15 py-8 sm:grid-cols-[.18fr_.42fr_1fr] sm:items-start sm:gap-8 sm:py-10"><span className="text-sm font-black text-orange-400">{step.number}</span><h3 className="text-2xl font-black tracking-[-.035em] sm:text-3xl">{step.title}</h3><p className="max-w-2xl leading-7 text-slate-400">{step.text}</p></article>)}</div><p className="mt-8 max-w-3xl text-sm leading-6 text-slate-400"><strong className="text-white">De productieplanning start</strong> zodra scope, betaling en de afgesproken bedrijfsinformatie, inhoud en materialen compleet zijn.</p>{full ? <div className="mt-10 border-l-2 border-orange-500 pl-5 text-slate-300"><strong className="text-white">Afhankelijkheden:</strong> gebundelde feedback, toegang tot externe accounts en tijdige goedkeuring houden de planning uitvoerbaar. Nieuwe wensen worden als wijziging beoordeeld.</div> : null}</div></section>;
}

function ProjectPreview({ project }: { project: (typeof projects)[number] }) {
  return <div className="relative aspect-[16/10] overflow-hidden rounded-[1.25rem] bg-[#07111f] p-5 text-white sm:p-8"><div className="absolute -right-14 -top-14 size-52 rounded-full opacity-70 blur-3xl" style={{ backgroundColor: project.accent }} /><div className="relative h-full overflow-hidden rounded-xl bg-[#f6f3ed] text-slate-950 shadow-2xl"><div className="flex items-center justify-between border-b border-slate-900/10 px-4 py-3"><strong className="text-xs">{project.name}</strong><div className="flex gap-3 text-[9px] font-bold text-slate-700"><span>Aanbod</span><span>Over ons</span><span>Contact</span></div></div><div className="grid h-[calc(100%-41px)] grid-cols-[1.2fr_.8fr]"><div className="flex flex-col justify-center p-5 sm:p-8"><span className="text-[9px] font-black uppercase tracking-wider text-orange-900">{project.type}</span><p className="mt-3 max-w-sm text-xl font-black leading-tight sm:text-3xl">{project.objective}</p><span className="mt-5 h-8 w-fit rounded-full bg-[#07111f] px-4 py-2 text-[9px] font-black text-white">Ontdek de aanpak</span></div><div className="m-3 rounded-lg" style={{ background: `linear-gradient(145deg, ${project.accent}, #07111f)` }} /></div></div></div>;
}

export function ProjectsSection({ showAll = false }: { showAll?: boolean }) {
  const shown = showAll ? projects : projects.slice(0, 4);
  return <section className="bg-[#f6f3ed] pb-12 pt-16 sm:pb-16 sm:pt-20 lg:pt-24"><div className="mx-auto max-w-[86rem] px-5 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><SectionHeading eyebrow="Voorbeeldconcepten" title="Maatwerk ziet er voor ieder bedrijf anders uit" description="Conceptuele voorbeelden met een eigen doelgroep, ontwerpdoel, pagina-opbouw en functies. Het zijn geen klantcases of resultaatclaims." />{!showAll ? <ButtonLink href="/voorbeelden" variant="secondary">Bekijk alle voorbeelden</ButtonLink> : null}</div><div className="mt-12 grid gap-x-6 gap-y-10 md:grid-cols-2 sm:mt-14">{shown.map((project) => <article id={project.slug} key={project.slug} className="scroll-mt-28"><ProjectPreview project={project} /><div className="py-5"><p className="text-[10px] font-black uppercase tracking-wider text-orange-800">Conceptontwerp · geen klantcase</p><h3 className="mt-3 text-3xl font-black tracking-[-0.045em] text-slate-950">{project.name}</h3><p className="mt-3 leading-7 text-slate-600"><strong>Doelgroep:</strong> {project.audience}</p><p className="mt-2 leading-7 text-slate-600"><strong>Ontwerpdoel:</strong> {project.objective}</p><p className="mt-2 text-sm text-slate-600"><strong>Pagina-opbouw:</strong> {project.pageStructure.join(" · ")}</p><p className="mt-2 text-sm text-slate-600"><strong>Functies:</strong> {project.features.join(" · ")}</p><Link href="/contact#advies" className="mt-4 inline-flex min-h-11 items-center gap-1 text-sm font-black text-slate-950">Bespreek jouw richting <ArrowUpRight className="size-4" /></Link></div></article>)}</div>{showAll ? <div className="mt-8 rounded-3xl bg-slate-100 p-7"><p className="max-w-3xl leading-7 text-slate-700"><strong className="text-slate-950">Transparant over voorbeeldwerk:</strong> alle getoonde concepten zijn intern ontwikkeld als demonstratie. Ze vertegenwoordigen geen bestaande klant of behaald bedrijfsresultaat.</p></div> : null}</div></section>;
}

export function FaqSection({ showAll = false }: { showAll?: boolean }) {
  const shown = showAll ? faqs : faqs.slice(0, 6);
  return <section className="bg-[#f6f3ed] py-24 sm:py-32 lg:py-40"><div className="mx-auto grid max-w-[86rem] gap-12 px-5 sm:px-8 lg:grid-cols-[.72fr_1.28fr] lg:px-10 lg:gap-20"><div><SectionHeading eyebrow="Veelgestelde vragen" title="Duidelijkheid vóór we beginnen" description="Over prijzen, onderhoud, branches, hosting en uitbreiden. Staat je vraag er niet bij? Neem gerust contact op." />{!showAll ? <ButtonLink href="/veelgestelde-vragen" variant="secondary" className="mt-7">Bekijk alle vragen</ButtonLink> : null}</div><div className="border-t border-slate-900/20">{shown.map((faq) => <details key={faq.question} className="group border-b border-slate-900/20 py-6"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-6 text-lg font-black text-slate-950 marker:hidden">{faq.question}<span className="shrink-0 text-2xl font-normal text-orange-500 transition-transform duration-200 group-open:rotate-45">+</span></summary><p className="max-w-2xl pb-2 pr-10 pt-4 leading-7 text-slate-600">{faq.answer}</p></details>)}</div></div></section>;
}

export function BottomCta() {
  return <section className="bg-orange-500 py-20 text-[#07111f] sm:py-24"><div className="mx-auto grid max-w-[86rem] gap-10 px-5 sm:px-8 lg:grid-cols-[1fr_auto] lg:items-end lg:px-10"><div><p className="text-xs font-black uppercase tracking-[.2em]">Klaar voor de volgende stap?</p><h2 className="mt-5 max-w-5xl text-4xl font-black leading-[1.02] tracking-[-0.05em] sm:text-5xl lg:text-6xl">Laat je website net zo professioneel werken als jouw bedrijf.</h2></div><ButtonLink href="/contact#advies" variant="secondary" className="shrink-0 border-slate-950/25 bg-transparent">Ontvang gratis websiteadvies</ButtonLink></div></section>;
}
